conky.config = {
    alignment = 'top_left',
    background = false,

    border_width = 0,
    cpu_avg_samples = 2,

    default_color = 'ffffff',
    double_buffer = true,

    draw_borders = false,
    draw_graph_borders = false,
    draw_outline = false,
    draw_shades = false,

    extra_newline = false,

    font = 'DejaVu Sans:size=10',
    gap_x = 30,
    gap_y = 80,

    minimum_width = 300,
    maximum_width = 300,

    net_avg_samples = 2,

    no_buffers = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    own_window_transparent = true,

    show_graph_range = false,
    show_graph_scale = false,

    update_interval = 1,

    use_xft = true,
    xftalpha = 1,
};

conky.text = [[

${if_running spotify}

${alignc}${font DejaVu Sans:bold:size=14}♫ SPOTIFY${font}

${voffset 8}${alignc}${font DejaVu Sans:bold:size=12}${exec playerctl -p spotify metadata --format '{{ title }}'}${font}

${alignc}${exec playerctl -p spotify metadata --format '{{ artist }}'}
${alignc}${exec playerctl -p spotify metadata --format '{{ album }}'}

${voffset 8}${alignc}${exec playerctl -p spotify status}

${voffset 5}${alignc}${exec playerctl -p spotify metadata --format '{{ position(position)}}' 2>/dev/null}

${endif}

]];

